const Account = {
    "id":"0vEELcHsEQvkLOwp93tO",
    "CD":"10175",
    "Contenedor":{
       "Nombre":"A1",
       "Id":"-NNlTF4ETy_Swj4LDxlu"
    },
    "Tenant":"TEST",
    "Cliente":{
       "Apodo":"123",
       "Nombre":"Publico General",
       "Id":"PUBLICOGENERAL"
    },
    "Mesero":{
       "Id":"-MbMuNzJDdWinVmCo1ja",
       "Nombre":"Juan Perez Lopez"
    },
    "Estatus":1,
    "DAYB":"-NNlSvUtB8k1Ry7n3WT9",
    "FechaCreacion":1722439647035,
    "TicketImpreso":false,
    "ECP":false,
    "Comensales":1,
    "DPDV":"AYB-CasaClubGolf",
    "Catalogo":[
       {
          "Descuentos":[
             
          ],
          "productoId":"2MUZFaEu729hUjfQ73GN",
          "PrecioBfCupon":15,
          "ExtraParams":{
             "CuentaData":{
                "CPI":1722532484956
             },
             "Venta":{
                "dpto":"-NNlSvUtB8k1Ry7n3WT9"
             }
          },
          "Notas":"",
          "DescuentosManuales":[
             
          ],
          "Origen":"-N7HkOCbljIyYwyJ7DPL",
          "producto":{
             "tags":[
                "Favoritas del chef",
                "Para compartir"
             ],
             "Categoria":"-NM4DecdrnUb0F9ovtxH"
          },
          "Orn":"-N7HkOCbljIyYwyJ7DPL",
          "internalId":"2MUZFaEu729hUjfQ73GN_-N7HkOCbljIyYwyJ7DPL5qr9t91s9uymxjh05uxc3p",
          "Tipo":"AYB-Producto",
          "Cantidad":1,
          "Tip":"AYB-Producto",
          "selected":false,
          "Precio":15,
          "CategoriaData":{
             "Activo":true,
             "products":[
                
             ],
             "Familia":"-NEm2nBoX4LkT_LqypyZ",
             "ZImp":"TICKET-PRINTER",
             "Departamento":"AYB-CasaClubGolf",
             "Nombre":"ENTRADAS",
             "id":"-NM4DecdrnUb0F9ovtxH"
          },
          "Pco":{
             "C":15,
             "M":"MXN"
          },
          "Mnd":"MXN",
          "Nombre":"Frutas picadas",
          "PrecioOriginal":15,
          "Moneda":"MXN",
          "name":"Frutas picadas",
          "Cnt":1,
          "Id":"2MUZFaEu729hUjfQ73GN",
          "Pcs":{
             "P":1,
             "C":0
          },
          "Cto":{
             "C":0,
             "M":"MXN"
          },
          "STip":"AYB-Cuenta",
          "Catalogo":[
             {
                "Catalogo":[
                   
                ],
                "Moneda":"MXN",
                "Tipo":"AYB-Insumo",
                "Extra":{
                   "AYB":{
                      "Mm":5,
                      "Rm":0,
                      "UM":"KGS"
                   }
                },
                "Id":"w5AMPQfioatJmPuJF8oC",
                "Cantidad":0.2
             }
          ],
          "_PC":0
       },
       {
          "PrecioOriginal":450,
          "Moneda":"MXN",
          "Cto":{
             "M":"MXN",
             "C":0
          },
          "producto":{
             "tags":[
                
             ],
             "Categoria":"-NM4E5Q84tF1-GzpYcqA"
          },
          "Origen":"-N7HkOCbljIyYwyJ7DPL",
          "Id":"CY3ZMQgrsSlEqNeTuVP4",
          "Cantidad":1,
          "internalId":"CY3ZMQgrsSlEqNeTuVP4_-N7HkOCbljIyYwyJ7DPL3gefi2dsb0k3hnepszss7r",
          "Cnt":1,
          "productoId":"CY3ZMQgrsSlEqNeTuVP4",
          "Precio":450,
          "DescuentosManuales":[
             
          ],
          "Tipo":"AYB-Producto",
          "_PC":0,
          "Orn":"-N7HkOCbljIyYwyJ7DPL",
          "Nombre":"Parrillada Mexicana",
          "CategoriaData":{
             "products":[
                
             ],
             "Nombre":"PLATO FUERTE",
             "ZImp":"-NReFid8GOhTHpwjQsCV",
             "id":"-NM4E5Q84tF1-GzpYcqA",
             "Familia":"-NEm2nBoX4LkT_LqypyZ",
             "Activo":true,
             "Departamento":"AYB-CasaClubGolf"
          },
          "Pcs":{
             "C":0,
             "P":1
          },
          "PrecioBfCupon":450,
          "Mnd":"MXN",
          "Tip":"AYB-Producto",
          "name":"Parrillada Mexicana",
          "STip":"AYB-Cuenta",
          "Pco":{
             "M":"MXN",
             "C":450
          },
          "Notas":"",
          "Descuentos":[
             
          ],
          "Catalogo":[
             {
                "Extra":{
                   "AYB":{
                      "UM":"Ltr",
                      "Mm":0,
                      "Rm":4
                   }
                },
                "Catalogo":[
                   {
                      "Id":"Izkv2wHArq9QNMpKUbyA",
                      "Moneda":"MXN",
                      "Catalogo":[
                         
                      ],
                      "Cantidad":0.5,
                      "Tipo":"AYB-Insumo",
                      "Extra":{
                         "AYB":{
                            "Rm":0,
                            "UM":"Pz"
                         }
                      }
                   },
                   {
                      "Id":"bLHwvYNKuvKJMQn7hSoM",
                      "Moneda":"MXN",
                      "Cantidad":4,
                      "Tipo":"AYB-Insumo",
                      "Extra":{
                         "AYB":{
                            "UM":"pz",
                            "Rm":0
                         }
                      },
                      "Catalogo":[
                         
                      ]
                   },
                   {
                      "Catalogo":[
                         
                      ],
                      "Extra":{
                         "AYB":{
                            "UM":"Pz",
                            "Rm":0
                         }
                      },
                      "Cantidad":0.1,
                      "Tipo":"AYB-Insumo",
                      "Moneda":"MXN",
                      "Id":"JXhxATL1Ef9qugMEplzh"
                   },
                   {
                      "Tipo":"AYB-Insumo",
                      "Catalogo":[
                         
                      ],
                      "Extra":{
                         "AYB":{
                            "UM":"gr",
                            "Rm":0
                         }
                      },
                      "Moneda":"MXN",
                      "Cantidad":0.1,
                      "Id":"ihcyX1NWhk8TKPb8DT3u"
                   },
                   {
                      "Moneda":"MXN",
                      "Extra":{
                         "AYB":{
                            "UM":"Pz",
                            "Rm":0
                         }
                      },
                      "Tipo":"AYB-Insumo",
                      "Catalogo":[
                         
                      ],
                      "Id":"3GNpDTE7jHxDwRtODKYa",
                      "Cantidad":0.5
                   },
                   {
                      "Cantidad":0.2,
                      "Id":"OLhdoIsDO0r6fr1kqKcp",
                      "Tipo":"AYB-Insumo",
                      "Extra":{
                         "AYB":{
                            "Rm":0,
                            "UM":"Kg"
                         }
                      },
                      "Moneda":"MXN",
                      "Catalogo":[
                         
                      ]
                   },
                   {
                      "Extra":{
                         "AYB":{
                            "Rm":0,
                            "UM":"Pz"
                         }
                      },
                      "Id":"GC6IFb2J1CbYb77Cdomk",
                      "Catalogo":[
                         
                      ],
                      "Moneda":"MXN",
                      "Tipo":"AYB-Insumo",
                      "Cantidad":4
                   }
                ],
                "Cantidad":0.3,
                "Id":"AeF13gR86qyADnFBeg6K",
                "Tipo":"AYB-ICompuesto",
                "Moneda":"MXN"
             },
             {
                "Catalogo":[
                   
                ],
                "Moneda":"MXN",
                "Cantidad":0.3,
                "Id":"I6u1isuAeQhDHWz6dYKn",
                "Tipo":"AYB-Insumo",
                "Extra":{
                   "AYB":{
                      "UM":"Kg",
                      "Mm":0,
                      "Rm":0
                   }
                }
             },
             {
                "Moneda":"MXN",
                "Extra":{
                   "AYB":{
                      "Mm":0,
                      "Rm":0,
                      "UM":"Pz"
                   }
                },
                "Tipo":"AYB-Insumo",
                "Cantidad":3,
                "Catalogo":[
                   
                ],
                "Id":"XiNPnCz2aDEkqW5xs0ed"
             },
             {
                "Cantidad":0.2,
                "Catalogo":[
                   
                ],
                "Extra":{
                   "AYB":{
                      "Rm":0,
                      "UM":"Kg",
                      "Mm":0
                   }
                },
                "Tipo":"AYB-Insumo",
                "Id":"YQqUWZ52jSQkmRuKzMRW",
                "Moneda":"MXN"
             },
             {
                "Extra":{
                   "AYB":{
                      "Rm":0,
                      "Mm":0,
                      "UM":"Pz"
                   }
                },
                "Id":"ecvYrVA8O8vhGP6hYGka",
                "Catalogo":[
                   
                ],
                "Tipo":"AYB-Insumo",
                "Cantidad":1,
                "Moneda":"MXN"
             },
             {
                "Tipo":"AYB-Insumo",
                "Catalogo":[
                   
                ],
                "Moneda":"MXN",
                "Id":"Eq3r7GkkuUZojZWkwBZA",
                "Extra":{
                   "AYB":{
                      "Rm":0,
                      "Mm":5,
                      "UM":"KGS"
                   }
                },
                "Cantidad":1
             }
          ],
          "selected":false,
          "ExtraParams":{
             "Venta":{
                "dpto":"-NNlSvUtB8k1Ry7n3WT9"
             },
             "CuentaData":{
                "CPI":1722532597126
             }
          }
       },
       {
          "internalId":"0mV3Yvs1iRAaGQTs2UZL_-N7HkOCbljIyYwyJ7DPL9dpvj44fhuqnjsohsadqam",
          "Orn":"-N7HkOCbljIyYwyJ7DPL",
          "Precio":450,
          "Cantidad":1,
          "Origen":"-N7HkOCbljIyYwyJ7DPL",
          "PrecioOriginal":450,
          "name":"Molcajete de Pollo",
          "selected":false,
          "productoId":"0mV3Yvs1iRAaGQTs2UZL",
          "PrecioBfCupon":450,
          "_PC":0,
          "Descuentos":[
             
          ],
          "producto":{
             "tags":[
                "Promo 2x1"
             ],
             "Categoria":"-NM4ERcbnGAv3d_ynn8j"
          },
          "Id":"0mV3Yvs1iRAaGQTs2UZL",
          "STip":"AYB-Cuenta",
          "Tipo":"AYB-Producto",
          "Cnt":1,
          "DescuentosManuales":[
             
          ],
          "Cto":{
             "C":0,
             "M":"MXN"
          },
          "Tip":"AYB-Producto",
          "Pco":{
             "C":450,
             "M":"MXN"
          },
          "Pcs":{
             "C":0,
             "P":1
          },
          "ExtraParams":{
             "CuentaData":{
                "CPI":1722532794405
             },
             "Venta":{
                "dpto":"-NNlSvUtB8k1Ry7n3WT9"
             }
          },
          "CategoriaData":{
             "products":[
                
             ],
             "ZImp":"TICKET-PRINTER",
             "Departamento":"AYB-CasaClubGolf",
             "Familia":"-NEm2nBoX4LkT_LqypyZ",
             "Nombre":"MENU EJECUTIVO",
             "id":"-NM4ERcbnGAv3d_ynn8j",
             "Activo":true
          },
          "Notas":"",
          "Moneda":"MXN",
          "Catalogo":[
             {
                "Cantidad":0.3,
                "Id":"AeF13gR86qyADnFBeg6K",
                "Moneda":"MXN",
                "Extra":{
                   "AYB":{
                      "UM":"Ltr",
                      "Rm":4,
                      "Mm":0
                   }
                },
                "Tipo":"AYB-ICompuesto",
                "Catalogo":[
                   {
                      "Id":"Izkv2wHArq9QNMpKUbyA",
                      "Moneda":"MXN",
                      "Catalogo":[
                         
                      ],
                      "Tipo":"AYB-Insumo",
                      "Extra":{
                         "AYB":{
                            "Rm":0,
                            "UM":"Pz"
                         }
                      },
                      "Cantidad":0.5
                   },
                   {
                      "Id":"bLHwvYNKuvKJMQn7hSoM",
                      "Catalogo":[
                         
                      ],
                      "Tipo":"AYB-Insumo",
                      "Cantidad":4,
                      "Moneda":"MXN",
                      "Extra":{
                         "AYB":{
                            "UM":"pz",
                            "Rm":0
                         }
                      }
                   },
                   {
                      "Tipo":"AYB-Insumo",
                      "Moneda":"MXN",
                      "Catalogo":[
                         
                      ],
                      "Id":"JXhxATL1Ef9qugMEplzh",
                      "Cantidad":0.1,
                      "Extra":{
                         "AYB":{
                            "Rm":0,
                            "UM":"Pz"
                         }
                      }
                   },
                   {
                      "Id":"ihcyX1NWhk8TKPb8DT3u",
                      "Cantidad":0.1,
                      "Extra":{
                         "AYB":{
                            "Rm":0,
                            "UM":"gr"
                         }
                      },
                      "Moneda":"MXN",
                      "Tipo":"AYB-Insumo",
                      "Catalogo":[
                         
                      ]
                   },
                   {
                      "Id":"3GNpDTE7jHxDwRtODKYa",
                      "Extra":{
                         "AYB":{
                            "UM":"Pz",
                            "Rm":0
                         }
                      },
                      "Tipo":"AYB-Insumo",
                      "Cantidad":0.5,
                      "Moneda":"MXN",
                      "Catalogo":[
                         
                      ]
                   },
                   {
                      "Id":"OLhdoIsDO0r6fr1kqKcp",
                      "Moneda":"MXN",
                      "Tipo":"AYB-Insumo",
                      "Catalogo":[
                         
                      ],
                      "Cantidad":0.2,
                      "Extra":{
                         "AYB":{
                            "Rm":0,
                            "UM":"Kg"
                         }
                      }
                   },
                   {
                      "Catalogo":[
                         
                      ],
                      "Moneda":"MXN",
                      "Id":"GC6IFb2J1CbYb77Cdomk",
                      "Extra":{
                         "AYB":{
                            "Rm":0,
                            "UM":"Pz"
                         }
                      },
                      "Tipo":"AYB-Insumo",
                      "Cantidad":4
                   }
                ]
             },
             {
                "Moneda":"MXN",
                "Id":"I6u1isuAeQhDHWz6dYKn",
                "Extra":{
                   "AYB":{
                      "Mm":0,
                      "UM":"Kg",
                      "Rm":0
                   }
                },
                "Catalogo":[
                   
                ],
                "Cantidad":0.3,
                "Tipo":"AYB-Insumo"
             },
             {
                "Extra":{
                   "AYB":{
                      "Mm":0,
                      "UM":"Pz",
                      "Rm":0
                   }
                },
                "Catalogo":[
                   
                ],
                "Id":"XiNPnCz2aDEkqW5xs0ed",
                "Tipo":"AYB-Insumo",
                "Moneda":"MXN",
                "Cantidad":3
             },
             {
                "Cantidad":0.2,
                "Extra":{
                   "AYB":{
                      "Mm":0,
                      "Rm":0,
                      "UM":"Kg"
                   }
                },
                "Catalogo":[
                   
                ],
                "Moneda":"MXN",
                "Tipo":"AYB-Insumo",
                "Id":"YQqUWZ52jSQkmRuKzMRW"
             },
             {
                "Catalogo":[
                   
                ],
                "Cantidad":1,
                "Id":"ecvYrVA8O8vhGP6hYGka",
                "Moneda":"MXN",
                "Tipo":"AYB-Insumo",
                "Extra":{
                   "AYB":{
                      "Rm":0,
                      "Mm":0,
                      "UM":"Pz"
                   }
                }
             },
             {
                "Extra":{
                   "AYB":{
                      "UM":"KGS",
                      "Rm":0,
                      "Mm":5
                   }
                },
                "Moneda":"MXN",
                "Tipo":"AYB-Insumo",
                "Cantidad":1,
                "Id":"Eq3r7GkkuUZojZWkwBZA",
                "Catalogo":[
                   
                ]
             }
          ],
          "Mnd":"MXN",
          "Nombre":"Molcajete de Pollo"
       },
       {
          "PrecioOriginal":15,
          "Tipo":"AYB-Producto",
          "_PC":0,
          "producto":{
             "Categoria":"-NM4ERcbnGAv3d_ynn8j",
             "tags":[
                "Favoritas del chef",
                "Para compartir"
             ]
          },
          "Precio":15,
          "Cantidad":1,
          "Cnt":1,
          "name":"Pollo a la marinera",
          "DescuentosManuales":[
             
          ],
          "Mnd":"MXN",
          "CategoriaData":{
             "id":"-NM4ERcbnGAv3d_ynn8j",
             "ZImp":"TICKET-PRINTER",
             "Departamento":"AYB-CasaClubGolf",
             "products":[
                
             ],
             "Familia":"-NEm2nBoX4LkT_LqypyZ",
             "Nombre":"MENU EJECUTIVO",
             "Activo":true
          },
          "Notas":"",
          "Orn":"-N7HkOCbljIyYwyJ7DPL",
          "Origen":"-N7HkOCbljIyYwyJ7DPL",
          "Tip":"AYB-Producto",
          "productoId":"VYoszbHmjufuvdSDSNTv",
          "PrecioBfCupon":15,
          "ExtraParams":{
             "CuentaData":{
                "CPI":1722532794406
             },
             "Venta":{
                "dpto":"-NNlSvUtB8k1Ry7n3WT9"
             }
          },
          "Moneda":"MXN",
          "Pcs":{
             "C":0,
             "P":1
          },
          "internalId":"VYoszbHmjufuvdSDSNTv_-N7HkOCbljIyYwyJ7DPLmubzr56fhga2qqmblebyf",
          "Descuentos":[
             
          ],
          "Cto":{
             "C":0,
             "M":"MXN"
          },
          "Nombre":"Pollo a la marinera",
          "Id":"VYoszbHmjufuvdSDSNTv",
          "STip":"AYB-Cuenta",
          "Catalogo":[
             {
                "Moneda":"MXN",
                "Extra":{
                   "AYB":{
                      "Mm":5,
                      "UM":"KGS",
                      "Rm":0
                   }
                },
                "Tipo":"AYB-Insumo",
                "Cantidad":0.2,
                "Id":"w5AMPQfioatJmPuJF8oC",
                "Catalogo":[
                   
                ]
             }
          ],
          "selected":false,
          "Pco":{
             "M":"MXN",
             "C":15
          }
       }
    ],
    "Departamento":"AYB-CasaClubGolf"
}

export default Account